config/routes.rb
Rails.application.routes.draw do


resources :tasks do
  resources :sub_tasks, only: :new
  member do
    post 'complete'
    post 'undone'
  end
end
resources :sub_tasks, except: :new do
  member do
    post 'complete'
    post 'undone'
  end
end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  validates :task_id, presence: true

  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :sub_tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :find_sub_task, only:[:edit,:update,:show, :destroy, :complete, :undone]
  def new
    @sub_task = SubTask.new(task_id: params[:task_id])


  end

  def create
    @sub_task = SubTask.new(sub_task_params)
    if @sub_task.save!
      redirect_to task_url(@sub_task.task)
    else
      flash.now[:errors]=@sub_task.errors.full_message
      render :new
    end

  end

  def edit
  end

  def update
    @sub_task.update!(sub_task_params)
    redirect_to task_url(@sub_task.task)
  end

  def show
  end


  def destroy
  end

  def complete
    @sub_task = SubTask.find(params[:id])
    @sub_task.update!(done:true)
    redirect_to task_url(@sub_task.task)
  end

  def undone
    @sub_task = SubTask.find(params[:id])
    @sub_task.update!(done:false)
    redirect_to task_url(@sub_task.task)
  end

  private

  def sub_task_params
    params.require(:sub_task).permit(:title,:body,:task_id)
  end

  def find_sub_task
    @sub_task = SubTask.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only:[:edit,:update,:show, :destroy, :complete, :undone, :all_completed]
  before_action :check_all_completed, only: :complete

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_url
    else
      flash.now[:errors] = @task.errors.full_message
      render :new
    end
  end

  def edit

  end

  def update
    @task.update!(task_params)
    redirect_to tasks_url
  end

  def show
    @sub_tasks = @task.sub_tasks.sort_by &:created_at
  end

  def index
    @done_tasks = Task.all.select{|task| task.done == true}
    @undone_tasks = Task.all.select{|task| task.done == false}
  end

  def destroy

    @task.destroy!
    redirect_to tasks_url
  end

  def complete
    @task.update!(done:true)
    redirect_to tasks_url
  end

  def undone
    @task.update!(done:false)
    redirect_to tasks_url
  end

  private
  def task_params
    params.require(:task).permit(:title,:body,:done)
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def check_all_completed
    unless all_completed
      flash[:errors] = ['Finish all sub_tasks first!']
      redirect_to tasks_url
    end
  end

  def all_completed
    @task.sub_tasks.where(done:false) == [];
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= flash[:errors] %>
    <%= yield %>
  </body>
</html>

app/views/sub_tasks/_form.html.erb
<h1><%= @sub_task.persisted? ? 'Edit Sub_Task' : 'New Sub_Task' %></h1>
<% action_url = @sub_task.persisted? ? sub_task_url(@sub_task) : sub_tasks_url%>
<% http_method = @sub_task.persisted? ? 'patch' : 'post' %>

<form class="" action="<%=action_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token  %>">
  <input type="hidden" name="_method" value="<%=http_method%>">
  <label for="">
    Title
    <input type="text" name="sub_task[title]" value="<%=@sub_task.title %>">
  </label>
  <label for="">
    Body
    <input type="textarea" name="sub_task[body]" value="<%=@sub_task.body%>">
  </label>
    <input type="hidden" name="sub_task[task_id]" value="<%=@sub_task.task_id%>">
  <input type="submit" name="" value="Submit">
</form>

app/views/sub_tasks/create.html.erb
<h1>SubTasks#create</h1>
<p>Find me in app/views/sub_tasks/create.html.erb</p>

app/views/sub_tasks/destroy.html.erb
<h1>SubTasks#destroy</h1>
<p>Find me in app/views/sub_tasks/destroy.html.erb</p>

app/views/sub_tasks/edit.html.erb
<%= render 'form' %>

app/views/sub_tasks/index.html.erb
<h1>SubTasks#index</h1>
<p>Find me in app/views/sub_tasks/index.html.erb</p>

app/views/sub_tasks/new.html.erb
<%= render 'form' %>

app/views/sub_tasks/show.html.erb
<h1>Title</h1>
<%= @sub_task.title %>
<h3>Body</h3>
<%= @sub_task.body %>
<br>
<br>
<%= link_to 'Edit', edit_sub_task_url(@sub_task) %>
<br>
<br>
<%= link_to 'Main Task', task_url(@sub_task.task) %>

app/views/sub_tasks/update.html.erb
<h1>SubTasks#update</h1>
<p>Find me in app/views/sub_tasks/update.html.erb</p>

app/views/tasks/_form.html.erb
<h1><%= @task.persisted? ? 'Edit Task' : 'New Task' %></h1>
<% action_url = @task.persisted? ? task_url(@task) : tasks_url%>
<% http_method = @task.persisted? ? 'patch' : 'post' %>

<form class="" action="<%=action_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token  %>">
  <input type="hidden" name="_method" value="<%=http_method%>">
  <label for="">
    Title
    <input type="text" name="task[title]" value="<%=@task.title %>">
  </label>
  <label for="">
  Body
  <input type="textarea" name="task[body]" value="<%=@task.body %>">
  </label>
  <input type="submit" name="" value="Submit">
</form>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/index.html.erb
<style media="screen">
  table, th, td{
    border: 1px solid black;
    border-collapse: collapse;
    padding: 30px;
    text-align: center

  }
</style>
<h1>Tasks</h1>
<h1>
  <%= button_to 'New Task', new_task_url, method: :get%>
</h1>
<table style="width:50%">
  <tr>
    <th>To Dos</th>
    <th>Completed</th>
  </tr>
  <% length = @done_tasks.length > @undone_tasks.length ? @done_tasks.length : @undone_tasks.length %>
  <% for i in 0...length %>
    <% undone = @undone_tasks[i] %>
    <% done = @done_tasks[i] %>
    <tr>
      <td>
        <% if undone %>
          <% comp_ratio = "#{undone.sub_tasks.where(done:true).length} / #{undone.sub_tasks.length}" %>
          <h2><%=link_to undone.title, task_url(undone)%>  <%= comp_ratio %></h2>
          <%=button_to 'Complete', complete_task_url(undone) %>
          <%= button_to 'Delete', task_url(undone), method: :delete %>
        <% end %>
      </td>
      <td>
        <% if done %>
          <% comp_ratio = "#{done.sub_tasks.where(done:true).length} / #{done.sub_tasks.length}" %>
          <h2><%=link_to done.title, task_url(done)%>  <%= comp_ratio %></h2>
          <%= button_to "Undone", undone_task_url(done) %>
          <%= button_to 'Delete', task_url(done), method: :delete %>

        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<style media="screen">
.completed {
  color:red;
}
</style>

<h1><%=@task.title %></h1>
<p><%= @task.body %></p>

<%= button_to 'Edit Task', edit_task_url(@task), method: :get %>
<%= button_to 'Delete Task', task_url(@task), method: :delete %>
<%= button_to "All Tasks", tasks_url, method: :get %>
<%= button_to 'Add a new sub_task', new_task_sub_task_url(@task), method: :get %>

<ol>
  <% @sub_tasks.each do |sub_task| %>
    <% button_name = sub_task.done ? 'Undone' : 'Complete' %>
    <% action_url = sub_task.done ? undone_sub_task_url(sub_task) : complete_sub_task_url(sub_task) %>
    <li>
      <% if sub_task.done %>
        <strike><%= link_to sub_task.title, sub_task_url(sub_task)%> </strike>
      <% else %>
        <%= link_to sub_task.title, sub_task_url(sub_task)%>
      <% end %>
        <%= button_to button_name, action_url %>
    </li>
  <% end %>
</ol>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>